"""empty message

Revision ID: 0396a5ed0d5f
Revises: 7c7c6a4e2b05
Create Date: 2023-06-02 17:20:11.754687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0396a5ed0d5f'
down_revision = '7c7c6a4e2b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.alter_column('directors',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('writers',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.alter_column('writers',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('directors',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
