"""empty message

Revision ID: 401c93a11b12
Revises: b11aaa41b110
Create Date: 2023-06-01 16:37:44.511355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401c93a11b12'
down_revision = 'b11aaa41b110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.drop_index('ix_title_crew_directors')
        batch_op.drop_index('ix_title_crew_writers')

    with op.batch_alter_table('title_episode', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'title_basics', ['parentTconst'], ['tconst'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_episode', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.create_index('ix_title_crew_writers', ['writers'], unique=False)
        batch_op.create_index('ix_title_crew_directors', ['directors'], unique=False)

    # ### end Alembic commands ###
