"""empty message

Revision ID: 709e05471463
Revises: 9e4060ae9dd3
Create Date: 2023-06-03 21:28:29.887716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709e05471463'
down_revision = '9e4060ae9dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_episode', schema=None) as batch_op:
        batch_op.drop_constraint('title_episode_parentTconst_fkey', type_='foreignkey')

    with op.batch_alter_table('title_ratings', schema=None) as batch_op:
        batch_op.drop_constraint('title_ratings_tconst_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_ratings', schema=None) as batch_op:
        batch_op.create_foreign_key('title_ratings_tconst_fkey', 'title_basics', ['tconst'], ['tconst'])

    with op.batch_alter_table('title_episode', schema=None) as batch_op:
        batch_op.create_foreign_key('title_episode_parentTconst_fkey', 'title_basics', ['parentTconst'], ['tconst'])

    # ### end Alembic commands ###
