"""empty message

Revision ID: 885715eb2a6f
Revises: 401c93a11b12
Create Date: 2023-06-02 15:40:40.791648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885715eb2a6f'
down_revision = '401c93a11b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_ratings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'title_basics', ['tconst'], ['tconst'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
