"""empty message

Revision ID: b11aaa41b110
Revises: be8bdcea21ff
Create Date: 2023-05-31 16:05:18.378440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11aaa41b110'
down_revision = 'be8bdcea21ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_basics',
    sa.Column('nconst', sa.String(length=200), nullable=False),
    sa.Column('primaryName', sa.String(length=200), nullable=True),
    sa.Column('birthYear', sa.Integer(), nullable=True),
    sa.Column('deathYear', sa.Integer(), nullable=True),
    sa.Column('primaryProfession', sa.String(length=500), nullable=True),
    sa.Column('knownForTitles', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('nconst')
    )
    op.create_table('title_akas',
    sa.Column('titleId', sa.String(length=200), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=200), nullable=True),
    sa.Column('types', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.String(length=200), nullable=True),
    sa.Column('isOriginalTitle', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('titleId')
    )
    op.create_table('title_basics',
    sa.Column('tconst', sa.String(length=200), nullable=False),
    sa.Column('titleType', sa.String(length=200), nullable=True),
    sa.Column('primaryTitle', sa.String(length=200), nullable=True),
    sa.Column('originalTitle', sa.String(length=200), nullable=True),
    sa.Column('isAdult', sa.Boolean(), nullable=True),
    sa.Column('startYear', sa.Integer(), nullable=True),
    sa.Column('endYear', sa.Integer(), nullable=True),
    sa.Column('runtimeMinutes', sa.String(length=200), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_episode',
    sa.Column('tconst', sa.String(length=200), nullable=False),
    sa.Column('parentTconst', sa.String(length=200), nullable=True),
    sa.Column('seasonNumber', sa.Integer(), nullable=True),
    sa.Column('episodeNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_ratings',
    sa.Column('tconst', sa.String(length=200), nullable=False),
    sa.Column('averageRating', sa.Float(), nullable=True),
    sa.Column('numVotes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_ratings')
    op.drop_table('title_episode')
    op.drop_table('title_basics')
    op.drop_table('title_akas')
    op.drop_table('name_basics')
    # ### end Alembic commands ###
