"""empty message

Revision ID: be8bdcea21ff
Revises: 
Create Date: 2023-05-31 15:33:27.513862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8bdcea21ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_crew',
    sa.Column('tconst', sa.String(length=64), nullable=False),
    sa.Column('directors', sa.String(length=64), nullable=True),
    sa.Column('writers', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_crew_directors'), ['directors'], unique=False)
        batch_op.create_index(batch_op.f('ix_title_crew_writers'), ['writers'], unique=False)

    op.drop_table('TitleRatings')
    op.drop_table('TitleAkas')
    op.drop_table('TitlePrincipals')
    op.drop_table('TitleCrew')
    op.drop_table('TitleBasics')
    op.drop_table('NameBasics')
    op.drop_table('TitleEpisode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TitleEpisode',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parentTconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('seasonNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('episodeNumber', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('NameBasics',
    sa.Column('nconst', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('primaryName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deathYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primaryProfession', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('knownForTitles', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('nconst', name='NameBasics_pkey')
    )
    op.create_table('TitleBasics',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('titleType', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primaryTitle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('originalTitle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isAdult', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('startYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endYear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('runtimeMinutes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('TitleCrew',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('directors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('writers', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('TitlePrincipals',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordering', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('character', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('TitleAkas',
    sa.Column('titleId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordering', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attributes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isOriginalTitle', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('TitleRatings',
    sa.Column('tconst', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('averageRating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('numVotes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('title_crew', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_crew_writers'))
        batch_op.drop_index(batch_op.f('ix_title_crew_directors'))

    op.drop_table('title_crew')
    # ### end Alembic commands ###
